-- AlterTable
ALTER TABLE `customer` MODIFY `type` ENUM('ANALOG', 'INET', 'DIGITAL') NOT NULL DEFAULT 'INET';

-- AlterTable
ALTER TABLE `user` MODIFY `role` ENUM('KASIR', 'SUPERADMIN') NOT NULL DEFAULT 'KASIR';
